import { RxDashboard } from "react-icons/rx";
import { PiExam, PiStudent, PiUserList } from "react-icons/pi";
import {
  MdAccountBalance,
  MdCurrencyRupee,
  MdFingerprint,
  MdFormatListNumbered,
  MdManageAccounts,
  MdOnlinePrediction,
  MdOutlineAssignment,
  MdOutlineBedroomChild,
  MdOutlineDeleteSweep,
  MdOutlineFactCheck,
  MdOutlineFolderSpecial,
  MdOutlineHomeWork,
  MdOutlineLibraryBooks,
  MdOutlineMobileFriendly,
  MdOutlinePayment,
  MdOutlinePayments,
  MdOutlineSummarize,
  MdOutlineVerifiedUser,
  MdPeople,
  MdSchool,
  MdSubject,
  MdNextPlan,
  MdRequestQuote,
} from "react-icons/md";
import {
  FaBus,
  FaMoneyCheckAlt,
  FaOilCan,
  FaRegAddressCard,
  FaRegIdCard,
  FaSms,
  FaUserCog,
  FaUsers,
  FaWpforms,
} from "react-icons/fa";
import {
  LiaBarcodeSolid,
  LiaBirthdayCakeSolid,
  LiaClipboardListSolid,
  LiaRouteSolid,
} from "react-icons/lia";
import {
  BsBank2,
  BsBookshelf,
  BsCartCheck,
  BsCash,
  BsCashCoin,
  BsPeople,
  BsPersonBadge,
  BsPersonFillCheck,
} from "react-icons/bs";
import { FaRegClock } from "react-icons/fa";
import { FaComputer, FaHotel, FaRankingStar } from "react-icons/fa6";
import { CiBank, CiDiscount1 } from "react-icons/ci";
import {
  TbAlertSquare,
  TbCalendarDue,
  TbCirclesRelation,
  TbDeviceMobileMessage,
  TbFaceId,
  TbGenderTransgender,
  TbHexagonLetterC,
  TbReport,
  TbReportMoney,
  TbReportSearch,
  TbShoppingCartDiscount,
} from "react-icons/tb";
import { BiBus, BiMessage, BiMobile, BiPhotoAlbum } from "react-icons/bi";
import {
  GiAges,
  GiBrokenBone,
  GiBusStop,
  GiExpense,
  GiMachineGun,
  GiNotebook,
  GiPathDistance,
  GiTeacher,
  GiTeamUpgrade,
} from "react-icons/gi";
import { LuUsers } from "react-icons/lu";
import {
  IoBookSharp,
  IoCalendarOutline,
  IoFingerPrintSharp,
  IoLibraryOutline,
  IoTicketOutline,
} from "react-icons/io5";
import { CgProfile } from "react-icons/cg";
import {
  HiDevicePhoneMobile,
  HiOutlineClipboardDocumentList,
  HiOutlineCurrencyRupee,
} from "react-icons/hi2";
import { getLocalStorageItem } from "@/utils/LocalStorage";
import { RiAdminLine, RiFileTransferLine } from "react-icons/ri";
import { PERMISSIONS } from "./PermissionConstant";
import { GrCatalog, GrDocumentDownload } from "react-icons/gr";
import { SearchIcon, SettingsIcon } from "@chakra-ui/icons";
import { CiBookmarkCheck } from "react-icons/ci";
import { FaPenNib } from "react-icons/fa";
import { SiGoogleclassroom } from "react-icons/si";

export const SidebarItems =
  getLocalStorageItem("role") === "sys-admin"
    ? [
        {
          name: "Dashboard",
          icon: <RxDashboard />,
          key: "dashboard",
          href: "/",
        },
        {
          name: "Staff",
          icon: <BsPeople />,
          key: "staff",
          href: "/staff-admin",
          children: [
            {
              name: "Roles",
              icon: <FaUserCog />,
              href: "/super-admin/roles",
            },
            {
              name: "Designation",
              icon: <LuUsers />,
              href: "/staff-admin/designation",
            },
            {
              name: "Staff List",
              icon: <MdNextPlan />,
              href: "/staff-admin/stafflist",
            },
          ],
        },
        {
          name: "ERP Info",
          icon: <FaComputer />,
          key: "erp",
          href: "/client",
          children: [
            {
              name: "Orgnization Register Request",
              icon: <MdPeople />,
              href: "/client/registration",
            },
            {
              name: "Orgnization Review List",
              icon: <MdPeople />,
              href: "/client/activation",
            },
            {
              name: "Orgnization List",
              icon: <MdPeople />,
              href: "/client/list",
            },
          ],
        },
        {
          name: "App Info",
          icon: <BiMobile />,
          key: "app",
          href: "/client",
          children: [
            {
              name: "App Register Request",
              icon: <MdPeople />,
              href: "/client/app-request",
            },
            // {
            //   name: "App Order List",
            //   icon: <LiaClipboardListSolid />,
            //   href: "/client/order-list",
            // },
            {
              name: "App Orgnization Review List",
              icon: <LiaClipboardListSolid />,
              href: "/client/app-activation",
            },
            {
              name: "App Orgnization List",
              icon: <LiaClipboardListSolid />,
              href: "/client/app-client-list",
            },
          ],
        },
        {
          name: "Plan",
          icon: <MdNextPlan />,
          key: "plan",
          href: "/plan",
          children: [
            {
              name: "Plan",
              icon: <MdNextPlan />,
              href: "/plan/permissions",
            },
          ],
        },
        {
          name: "Message",
          icon: <BiMessage />,
          key: "Message",
          href: "/Message",
          children: [
            {
              name: "SMS Template",
              icon: <MdOutlineLibraryBooks />,
              href: "/Message/message-template",
            },
            {
              name: "SMS Account Request",
              icon: <MdRequestQuote />,
              href: "/Message/MessageRequest",
            },
            {
              name: "SMS Account Approved",
              icon: <MdOutlineVerifiedUser />,
              href: "/Message/MessageApproved",
            },
            {
              name: "Bulk SMS Request",
              icon: <MdOutlineMobileFriendly />,
              href: "/Message/MessageRequestMore",
            },
          ],
        },
        {
          name: "Banks",
          icon: <PiStudent />,
          key: "banks",
          href: "/banks",
        },
        {
          name: "Biometric",
          icon: <TbFaceId />,
          key: "biometric",
          href: "/biometric",
        },
      ]
    : [
        {
          name: "Dashboard",
          icon: <RxDashboard />,
          key: "dashboard",
          href: "/",
        },
        {
          name: "Reception",
          icon: <MdOutlinePayments />,
          permission: PERMISSIONS.RECEPTION,
          key: "reception",
          href: "/reception/enquiry",
          children: [
            {
              name: "Enquiry",
              icon: <MdPeople />,
              href: "/reception/enquiry",
              permission: PERMISSIONS.ENQUIRY,
            },
            {
              name: "Enquiry List ",
              icon: <LiaClipboardListSolid />,
              href: "/reception/enquiry-list",
              permission: PERMISSIONS.ENQUIRY_LIST,
            },
            {
              name: "Collection Report",
              icon: <LiaClipboardListSolid />,
              href: "/reception/prospectsHistory",
              permission: PERMISSIONS.COLLECTION_REPORT,
            },
            {
              name: "Gate Pass",
              icon: <LiaClipboardListSolid />,
              href: "/reception/Gatepass-history",
              permission: PERMISSIONS.GATE_PASS_HISTORY,
            },
            {
              name: "Staff",
              icon: <LuUsers />,
              href: "/reception/staff",
              // permission: PERMISSIONS.STAFF,
            },

            // {
            //   name: "Enquiry Form",
            //   icon: <LiaClipboardListSolid />,
            //   href: "/reception/enquiryformprint",
            //   permission: PERMISSIONS.ENQUIRY_FORM,
            // },
            // {
            //   name: "Student Admission Form",
            //   icon: <LiaClipboardListSolid />,
            //   href: "/reception/Addmissionform",
            //   permission: PERMISSIONS.ADMISSION_FORM,
            // },
            // {
            //   name: "Admission Form",
            //   icon: <LiaClipboardListSolid />,
            //   href: "/reception/Form",
            //   permission: PERMISSIONS.ADMISSION_FORM,
            // },
          ],
        },
        {
          name: "Students",
          icon: <PiStudent />,
          permission: PERMISSIONS.STUDENT,
          key: "student",
          href: "/student",
          children: [
            {
              name: "Student Admission",
              icon: <FaWpforms />,
              href: "/student/student-admission",
              permission: PERMISSIONS.STUDENT_ADMISSION,
            },
            {
              name: "Students List",
              icon: <PiUserList />,
              href: "/student/student-list",
              permission: PERMISSIONS.STUDENT_LIST,
            },
            {
              name: "Subject Wise Report",
              icon: <PiUserList />,
              href: "/student/student-report",
              permission: PERMISSIONS.SUBJECT_WISE_REPORT,
            },
            {
              name: "Attendance Entry",
              icon: <BsPersonFillCheck />,
              href: "/student/attendance-entry",
              permission: PERMISSIONS.ATTENDANCE_ENTRY,
            },
            {
              name: "Attendance Report",
              icon: <MdFingerprint />,
              href: "/student/attendance-report",
              permission: PERMISSIONS.ATTENDANCE_REPORT,
            },
            {
              name: "ID Card",
              icon: <FaRegIdCard />,
              href: "/student/id-card",
              permission: PERMISSIONS.ID_CARD,
            },
            {
              name: "Download Document",
              icon: <GrDocumentDownload />,
              href: "/student/download-documents",
              permission: PERMISSIONS.DOWNLOAD_DOCUMENTS,
            },
            {
              name: "Custom Report",
              icon: <TbReport />,
              href: "/student/custom-report",
              permission: PERMISSIONS.CUSTOM_REPORT,
            },
            {
              name: "Category Report",
              icon: <TbGenderTransgender />,
              href: "/student/category-report",
              permission: PERMISSIONS.CATEGORY_REPORT,
            },
            {
              name: "Certificate",
              icon: <TbGenderTransgender />,
              href: "/student/certificate",
              permission: PERMISSIONS.CERTIFICATE,
            },
            {
              name: "Manage SR",
              icon: <TbReport />,
              href: "/student/manage-sr",
              permission: PERMISSIONS.MANAGE_SR,
            },
            {
              name: "SR List",
              icon: <MdSchool />,
              href: "/student/sr-list",
              permission: PERMISSIONS.SR_LIST,
            },
            {
              name: "Promotion",
              icon: <GiTeamUpgrade />,
              href: "/student/student-promotion",
              permission: PERMISSIONS.PROMOTION,
            },
            {
              name: "Siblings",
              icon: <TbCirclesRelation />,
              href: "/student/siblings",
              permission: PERMISSIONS.SIBLINGS,
            },
            {
              name: "Birth Day List",
              icon: <LiaBirthdayCakeSolid />,
              href: "/student/birth-day",
              permission: PERMISSIONS.BIRTH_DAY_LIST,
            },
            {
              name: "Age Wise Student",
              icon: <GiAges />,
              href: "/student/age-wise-student",
              permission: PERMISSIONS.AGE_WISE_STUDENT,
            },
            {
              name: "PTM Report",
              icon: <SiGoogleclassroom />,
              href: "/student/ptm-report",
              permission: PERMISSIONS.PTM_REPORT,
            },
            {
              name: "PTM",
              icon: <SiGoogleclassroom />,
              href: "/student/PtmReport",
              permission: PERMISSIONS.PTM,
            },
            {
              name: "Students Under Rustication",
              icon: <FaUsers />,
              href: "/student/rustication-list",
              permission: PERMISSIONS.RUSTICATION,
            },
            {
              name: "Student TC",
              icon: <RiFileTransferLine />,
              href: "/student/student-tc-report",
              permission: PERMISSIONS.STUDENT_TC,
            },
            {
              name: "RTE Student",
              icon: <MdOutlineFolderSpecial />,
              href: "/student/rte-student",
              permission: PERMISSIONS.RTE_STUDENT,
            },
            {
              name: "Delete Student",
              icon: <FaRegClock />,
              href: "/student/delete-fee",
              permission: PERMISSIONS.DELETED_STUDENT,
            },
            {
              name: "Deleted Student Records",
              icon: <MdOutlineDeleteSweep />,
              href: "/student/deleted-student",
              permission: PERMISSIONS.DELETED_STUDENT,
            },
          ],
        },
        {
          name: "Fees",
          icon: <MdOutlinePayments />,
          permission: PERMISSIONS.FEES,
          key: "fees",
          href: "/fees",
          children: [
            {
              name: "Fees Collection",
              icon: <MdCurrencyRupee />,
              href: "/fees/fees-collection",
              permission: PERMISSIONS.FEES_COLLECTION,
            },
            {
              name: "Fees List",
              icon: <MdOutlineFactCheck />,
              href: "/fees/fees-list",
              permission: PERMISSIONS.FEES_LIST,
            },
            {
              name: "User wise Collection",
              icon: <MdOutlineFactCheck />,
              href: "/fees/user-collection",
              permission: PERMISSIONS.USER_WISE_COLLECTION,
            },
            {
              name: "Online Transactions",
              icon: <MdOnlinePrediction />,
              href: "/fees/online-transactions",
              permission: PERMISSIONS.ONLINE_TRANSACTION,
            },
            {
              name: "Pending Fees",
              icon: <FaRegClock />,
              href: "/fees/pending-fees",
              permission: PERMISSIONS.PENDING_FEES,
            },
            {
              name: "Cheque Status",
              icon: <FaMoneyCheckAlt />,
              href: "/fees/cheque-status",
              permission: PERMISSIONS.CHEQUE_STATUS,
            },
            {
              name: "Fees Summary",
              icon: <MdOutlineSummarize />,
              href: "/fees/fees-summery",
              permission: PERMISSIONS.FEES_SUMMERY,
            },
            {
              name: "Discount Manage",
              icon: <TbShoppingCartDiscount />,
              href: "/fees/discount-request",
              permission: PERMISSIONS.DISCOUNT_REQUEST,
            },
            {
              name: "Fees Ledger",
              icon: <HiOutlineCurrencyRupee />,
              href: "/fees/fees-ledger",
              permission: PERMISSIONS.FEES_LEDGER,
            },
            {
              name: "Last Year Dues",
              icon: <TbCalendarDue />,
              href: "/fees/last-year-Due",
              permission: PERMISSIONS.LAST_YEAR_DUES,
            },
            {
              name: "Delete Fees",
              icon: <FaRegClock />,
              href: "/fees/delete-fee",
              permission: PERMISSIONS.DELETE_FEES,
            },
          ],
        },
        {
          name: "New",
          icon: <PiExam />,
          permission: PERMISSIONS.NEW_MASTER,
          key: "new",
          children: [
            {
              name: "Payable Report",
              icon: <TbReportMoney />,
              href: "/accounts/payable-report",
              permission: PERMISSIONS.PAYABLE_REPORT,
            },
            {
              name: "Payment Voucher",
              icon: <MdOutlinePayment />,
              href: "/accounts/payment-voucher",
              permission: PERMISSIONS.PAYMENT_VOUCHER,
            },
            {
              name: "TC Format",
              icon: <TbCalendarDue />,
              href: "/fees/Tcformat",
              permission: PERMISSIONS.PROGRESS_REPORT,
            },
            {
              name: "Progress Report",
              icon: <TbCalendarDue />,
              href: "/fees/Progressreport",
              permission: PERMISSIONS.PROGRESS_REPORT,
            },
            {
              name: "Monthly Fee Report",
              icon: <LiaClipboardListSolid />,
              href: "/reception/Monthlyreport",
              permission: PERMISSIONS.MONTHLY_REPORT,
            },
            {
              name: "Fees Receipt",
              icon: <TbCalendarDue />,
              href: "/fees/feesReceipt",
              permission: PERMISSIONS.FEES_RECEIPT,
            },
            {
              name: "Progress Report Type",
              icon: <TbCalendarDue />,
              href: "/fees/Progressreporttype",
              permission: PERMISSIONS.PROGRESS_REPORT_TYPE,
            },
            {
              name: "Character Certificate",
              icon: <MdOutlineDeleteSweep />,
              href: "/student/charactercertificate",
              permission: PERMISSIONS.CHARACTER_CERTIFICATE,
            },
            {
              name: "Bonafied Certificate",
              icon: <MdOutlineDeleteSweep />,
              href: "/student/bonafiedcertificate",
              permission: PERMISSIONS.BONAFIDED_CERTIFICATE,
            },
            {
              name: "Transfer Certificate",
              icon: <MdOutlineDeleteSweep />,
              href: "/student/transfercertificate",
              permission: PERMISSIONS.TRANSFER_CERTIFICATE,
            },
            {
              name: "Scholarship Form",
              icon: <MdOutlineDeleteSweep />,
              href: "/student/scholarshipform",
              permission: PERMISSIONS.SCHOLARSHIP_FORM,
            },
            {
              name: "Gate Pass",
              icon: <MdOutlineDeleteSweep />,
              href: "/student/gatepass",
              permission: PERMISSIONS.GATE_PASS,
            },
            {
              name: "General Voucher",
              icon: <IoTicketOutline />,
              href: "/accounts/general-voucher",
              permission: PERMISSIONS.GENERAL_VOUCHER,
            },
            {
              name: "Payable Report",
              icon: <TbReportMoney />,
              href: "/accounts/payable-report",
              permission: PERMISSIONS.PAYABLE_REPORT,
            },
            {
              name: "Payment Voucher",
              icon: <MdOutlinePayment />,
              href: "/accounts/payment-voucher",
              permission: PERMISSIONS.PAYMENT_VOUCHER,
            },
            {
              name: "Receipt Voucher",
              icon: <MdOutlinePayment />,
              href: "/accounts/receipt-voucher",
              permission: PERMISSIONS.RECEIPT_VOUCHER,
            },
            {
              name: "Exam Group",
              icon: <MdOutlineAssignment />,
              href: "/exam/exam-group",
              permission: PERMISSIONS.EXAM_GROUP,
            },
          ],
        },
        {
          name: "Exam",
          icon: <PiExam />,
          permission: PERMISSIONS.EXAM,
          key: "exam",
          children: [
            {
              name: "Create Exam",
              icon: <FaRegAddressCard />,
              href: "/exam/create-exam",
              permission: PERMISSIONS.CREATE_EXAM,
            },

            {
              name: "Assign Marks",
              icon: <MdOutlineAssignment />,
              href: "/exam/assign-exam",
              permission: PERMISSIONS.ASSIGN_EXAM,
            },
            {
              name: "Result Structure",
              icon: <TbReport />,
              href: "/exam/result-structure",
              permission: PERMISSIONS.RESULT_STRUCTURE,
            },
            {
              name: "Roll Number",
              icon: <MdFormatListNumbered />,
              href: "/exam/generate-rollno",
              permission: PERMISSIONS.GENERATE_ROLLNO,
            },
            {
              name: "Admit Card",
              icon: <FaRegAddressCard />,
              href: "/exam/admit-card",
              permission: PERMISSIONS.ADMIT_CARD,
            },
            {
              name: "Marks Entry",
              icon: <PiExam />,
              href: "/exam/marks-entry",
              permission: PERMISSIONS.MARKS_ENTRY,
            },
            {
              name: "Rank Report",
              icon: <FaRankingStar />,
              href: "/exam/rank-report",
              permission: PERMISSIONS.RANK_REPORT,
            },
            {
              name: "Publish Marksheet",
              icon: <MdOutlineAssignment />,
              href: "/exam/publish-marksheet",
              permission: PERMISSIONS.PUBLISH_MARKSHEET,
            },
            {
              name: "MarksSheet",
              icon: <FaPenNib />,
              href: "/exam/marks-sheet",
              permission: PERMISSIONS.MARKSHEET,
            },
          ],
        },
        {
          name: "Transport",
          icon: <BiBus />,
          permission: PERMISSIONS.TRANSPORT,
          key: "transport",
          href: "/transport",
          children: [
            {
              name: "Station",
              icon: <GiBusStop />,
              href: "/transport/station",
              permission: PERMISSIONS.STATION,
            },
            {
              name: "Driver Reg",
              icon: <FaRegAddressCard />,
              href: "/transport/driver-reg",
              permission: PERMISSIONS.DRIVER_REG,
            },
            {
              name: "Vehicle Reg",
              icon: <FaBus />,
              href: "/transport/vehicle-reg",
              permission: PERMISSIONS.VEHICLE_REG,
            },
            {
              name: "Route",
              icon: <LiaRouteSolid />,
              href: "/transport/route",
              permission: PERMISSIONS.ROUTE,
            },
            {
              name: "Fees Head",
              icon: <MdFormatListNumbered />,
              href: "/transport/fees-head",
              permission: PERMISSIONS.TRANS_FEES_HEAD,
            },
            {
              name: "Fees Define",
              icon: <FaRegAddressCard />,
              href: "/transport/fees-define",
              permission: PERMISSIONS.TRANS_FEES_DEFINE,
            },
            {
              name: "Student Registration",
              icon: <BsPersonBadge />,
              href: "/transport/transport-student",
              permission: PERMISSIONS.TRANSPORT_STUDENT,
            },
            {
              name: "Bulk Registration",
              icon: <BsPersonBadge />,
              href: "/transport/bulk-register",
              permission: PERMISSIONS.TRANSPORT_STUDENT,
            },
            {
              name: "Transporter Name",
              icon: <TbReportSearch />,
              href: "/transport/transporter-name",
              permission: PERMISSIONS.TRANSPORTER_NAME,
              isSeprate: getLocalStorageItem("isTransportCombine"),
            },
            {
              name: "Fees Collection",
              icon: <TbReportSearch />,
              href: "/transport/transport-fees",
              permission: PERMISSIONS.TRANS_FEES_COLLECTION,
              isSeprate: getLocalStorageItem("isTransportCombine"),
            },
            {
              name: "Fees List",
              icon: <TbReportSearch />,
              href: "/transport/transport-fees-list",
              permission: PERMISSIONS.TRANS_FEES_LIST,
              isSeprate: getLocalStorageItem("isTransportCombine"),
            },
            {
              name: "User wise Collection",
              icon: <MdOutlineFactCheck />,
              href: "/transport/user-collection",
              permission: PERMISSIONS.TRANS_USER_WISE_COLLECTION,
              isSeprate: getLocalStorageItem("isTransportCombine"),
            },
            {
              name: "Pending Fees",
              icon: <FaRegClock />,
              href: "/transport/pending-fees",
              permission: PERMISSIONS.PENDING_FEES,
            },
            {
              name: "Route wise Report",
              icon: <MdOutlineFactCheck />,
              href: "/transport/reports",
              permission: PERMISSIONS.ROUTE_WISE_REPORT,
            },

            {
              name: "Cheque Status",
              icon: <TbReportSearch />,
              href: "/transport/transport-cheque-status",
              permission: PERMISSIONS.TRANS_CHEQUE_STATUS,
            },
            {
              name: "Fees Ledger",
              icon: <TbReportSearch />,
              href: "/transport/transport-fees-ledger",
              permission: PERMISSIONS.TRANS_FEES_LEDGER,
              isSeprate: getLocalStorageItem("isTransportCombine"),
            },
            {
              name: "Fuel Issue",
              icon: <FaOilCan />,
              href: "/transport/issue-fual",
              permission: PERMISSIONS.FUEL_ISSUE,
            },

            {
              name: "Send Notification",
              icon: <FaSms />,
              href: "/transport/send-notification",
              permission: PERMISSIONS.SEND_NOTIFICATION,
            },
          ],
        },
        {
          name: "Hostel",
          icon: <FaHotel />,
          permission: PERMISSIONS.HOSTEL,
          key: "hostel",
          href: "/hostel",
          children: [
            {
              name: "Room Creation",
              icon: <MdOutlineBedroomChild />,
              href: "/hostel/room",
              permission: PERMISSIONS.ROOM,
            },
            {
              name: "Student Reg",
              icon: <FaRegAddressCard />,
              href: "/hostel/student-registration",
              permission: PERMISSIONS.STUDENT_REGISTRATION,
            },
            {
              name: "Student List",
              icon: <PiUserList />,
              href: "/hostel/student-list",
              permission: PERMISSIONS.STUDENT_LIST_HOSTEL,
            },
            {
              name: "ID Card",
              icon: <PiUserList />,
              href: "/hostel/id-card",
              permission: PERMISSIONS.ID_CARD_HOSTEL,
            },
            {
              name: "Hostel Fees",
              icon: <PiUserList />,
              href: "/hostel/hostel-fees",
              permission: PERMISSIONS.HOSTEL_FEES,
            },
            {
              name: "Attendance",
              icon: <PiUserList />,
              href: "/hostel/hostel-attendance",
              permission: PERMISSIONS.HOSTEL_ATTENDANCE,
            },
            {
              name: "Room Checkout",
              icon: <PiUserList />,
              href: "/hostel/room-checkout",
              permission: PERMISSIONS.ROOM_CHECKOUT,
            },
            {
              name: "Family Meet",
              icon: <PiUserList />,
              href: "/hostel/family-meet",
              permission: PERMISSIONS.FAMILY_MEET,
            },
          ],
        },
        {
          name: "Accounts",
          icon: <MdAccountBalance />,
          permission: PERMISSIONS.ACCOUNTS,
          key: "accounts",
          href: "/accounts",
          children: [
            {
              name: "Income Type",
              icon: <GiExpense />,
              href: "/accounts/income-type",
              permission: PERMISSIONS.INCOME_TYPE,
            },
            {
              name: "Ledger Creation",
              icon: <MdManageAccounts />,
              href: "/accounts/ledger-master",
              permission: PERMISSIONS.LEDGER_MASTER,
            },
            {
              name: "Expense Type",
              icon: <GiExpense />,
              href: "/accounts/expense-type",
              permission: PERMISSIONS.EXPENSE_TYPE,
            },
            {
              name: "Payment Voucher",
              icon: <MdOutlinePayments />,
              href: "/accounts/add-payable",
              permission: PERMISSIONS.ADD_PAYABLE,
            },

            {
              name: "Statement",
              icon: <BsCash />,
              href: "/accounts/statement",
              permission: PERMISSIONS.STATEMENT,
            },
            {
              name: "Expense Report",
              icon: <GiNotebook />,
              href: "/accounts/expense-report",
              permission: PERMISSIONS.EXPENSE_REPORT,
            },

            {
              name: "Bank Transaction",
              icon: <TbHexagonLetterC />,
              href: "/accounts/contra-voucher",
              permission: PERMISSIONS.CONTRA_VOUCHER,
            },
            {
              name: "Bank Transaction Report",
              icon: <BsBank2 />,
              href: "/accounts/book",
              permission: PERMISSIONS.ACCOUNT_BOOKS,
            },
            {
              name: "Cash Book",
              icon: <BsCashCoin />,
              href: "/accounts/cash-book",
              permission: PERMISSIONS.CASH_BOOK,
            },

            {
              name: "General Voucher",
              icon: <IoTicketOutline />,
              href: "/accounts/general-voucher",
              permission: PERMISSIONS.GENERAL_VOUCHER,
            },
            {
              name: "Receipt Voucher",
              icon: <MdOutlinePayment />,
              href: "/accounts/receipt-voucher",
              permission: PERMISSIONS.RECEIPT_VOUCHER,
            },
          ],
        },
        {
          name: "Library",
          icon: <IoLibraryOutline />,
          key: "library",
          permission: PERMISSIONS.LIBRARY,
          href: "/library",
          children: [
            {
              name: "Book/Journal Type",
              icon: <GrCatalog />,
              href: "/library/book-journal-type",
              permission: PERMISSIONS.BOOK_TYPE,
            },
            {
              name: "Catalog",
              icon: <GrCatalog />,
              href: "/library/catalog",
              permission: PERMISSIONS.CATALOG,
            },
            {
              name: "Book Vendor",
              icon: <GrCatalog />,
              href: "/library/book-vendor",
              permission: PERMISSIONS.BOOK_VENDOR,
            },
            {
              name: "Stock Entry",
              icon: <BsCartCheck />,
              href: "/library/stock-entry",
              permission: PERMISSIONS.PURCHASE_ENTRY,
            },
            {
              name: "Shelf Location",
              icon: <BsBookshelf />,
              href: "/library/shelf-location",
              permission: PERMISSIONS.SHELF_LOCATION,
            },
            {
              name: "Accession",
              icon: <LiaBarcodeSolid />,
              href: "/library/accession",
              permission: PERMISSIONS.ACCESSION,
            },
            {
              name: "Book Issue",
              icon: <IoBookSharp />,
              href: "/library/book-issue",
              permission: PERMISSIONS.BOOK_ISSUE,
            },
            {
              name: "Book Return",
              icon: <IoBookSharp />,
              href: "/library/book-return",
              permission: PERMISSIONS.BOOK_RETURN,
            },
            {
              name: "Current Stock",
              icon: <MdOutlineLibraryBooks />,
              href: "/library/current-stock",
              permission: PERMISSIONS.CURRENT_STOCK,
            },
            {
              name: "Search Book",
              icon: <SearchIcon />,
              href: "/library/search-book",
              permission: PERMISSIONS.SEARCH_BOOK,
            },
            {
              name: "Library Card",
              icon: <FaRegAddressCard />,
              href: "/library/library-card",
              permission: PERMISSIONS.LIBRARY_CARD,
            },
            {
              name: "Setting",
              icon: <SettingsIcon />,
              href: "/library/setting",
              permission: PERMISSIONS.LIBRARY_SETTING,
            },
          ],
        },
        {
          name: "Admin",
          icon: <RiAdminLine />,
          key: "admin",
          permission: PERMISSIONS.ADMIN,
          href: "/admin",
          children: [
            {
              name: "Users List",
              icon: <LuUsers />,
              href: "/admin/user-list",
              permission: PERMISSIONS.USER_LIST,
            },
            {
              name: "Roles",
              icon: <FaUserCog />,
              href: "/admin/roles",
              permission: PERMISSIONS.ROLES,
            },
            {
              name: "Calender",
              icon: <IoCalendarOutline />,
              href: "/app/calender",
              permission: PERMISSIONS.CALENDER,
            },
            {
              name: "Holiday List",
              icon: <IoCalendarOutline />,
              href: "/admin/holidays",
              permission: PERMISSIONS.HOLIDAYS,
            },
          ],
        },
        {
          name: "Staff",
          icon: <HiDevicePhoneMobile />,
          key: "staff",
          href: "/staff",
          permission: PERMISSIONS.STAFF_MAIN,
          children: [
            {
              name: "Designation",
              icon: <LuUsers />,
              href: "/staff/designation",
              permission: PERMISSIONS.STAFF_MAIN,
            },
            {
              name: "Staff List",
              icon: <LuUsers />,
              href: "/staff/staff-list",
              permission: PERMISSIONS.STAFF_LIST,
            },
            {
              name: "Payslip",
              icon: <LuUsers />,
              href: "/staff/payslip",
              permission: PERMISSIONS.PAYSLIP,
            },
            {
              name: "Salary List",
              icon: <LuUsers />,
              href: "/staff/salary-list",
              permission: PERMISSIONS.SALARY_LIST,
            },
            {
              name: "Attendance Entry",
              icon: <LuUsers />,
              href: "/staff/staff-attendance",
              permission: PERMISSIONS.STAFF_ATTENDANCE,
            },
            {
              name: "Attendance Report",
              icon: <MdFingerprint />,
              href: "/staff/attendance-report",
              permission: PERMISSIONS.STAFF_ATTENDANCE_REPORT,
            },
          ],
        },
        {
          name: "Stock",
          icon: <PiStudent />,
          permission: PERMISSIONS.STOCK,
          key: "stock",
          href: "/stock",
          children: [
            {
              name: "Supplier",
              icon: <MdPeople />,
              href: "/stock/suppliers",
              permission: PERMISSIONS.SUPPLIER,
            },
            {
              name: "Item Creation",
              icon: <MdPeople />,
              href: "/stock/item-creation",
              permission: PERMISSIONS.ITEM_CREATION,
            },
            {
              name: "Department",
              icon: <LiaClipboardListSolid />,
              href: "/stock/department",
              permission: PERMISSIONS.DEPARTMENT,
            },
            {
              name: "Stock Entry",
              icon: <LiaClipboardListSolid />,
              href: "/stock/stock-entry",
              permission: PERMISSIONS.STOCK_ENTRY,
            },
            {
              name: "Issue Item",
              icon: <LiaClipboardListSolid />,
              href: "/stock/issue-item",
              permission: PERMISSIONS.ISSUE_ITEM,
            },
            {
              name: "Damage Item",
              icon: <GiBrokenBone />,
              href: "/stock/damage-item",
              permission: PERMISSIONS.DAMAGE_ITEM,
            },
            {
              name: "Stock Report",
              icon: <LiaClipboardListSolid />,
              href: "/stock/stock-report",
              permission: PERMISSIONS.STOCK_REPORT,
            },
            {
              name: "Purchase Order",
              icon: <LiaClipboardListSolid />,
              href: "/stock/purchase-order",
              permission: PERMISSIONS.PURCHASE_ORDER,
            },
          ],
        },
        {
          name: "Sale",
          icon: <PiStudent />,
          permission: PERMISSIONS.SALE,
          key: "sale",
          href: "/sale",
          children: [
            {
              name: "Supplier",
              icon: <MdPeople />,
              href: "/sale/suppliers",
              permission: PERMISSIONS.SUPPLIER,
            },
            {
              name: "Item Creation",
              icon: <MdPeople />,
              href: "/sale/item-creation",
              permission: PERMISSIONS.ITEM_CREATION,
            },
            {
              name: "Stock Entry",
              icon: <LiaClipboardListSolid />,
              href: "/sale/stock-entry",
              permission: PERMISSIONS.STOCK_ENTRY,
            },
            {
              name: "Issue Item",
              icon: <LiaClipboardListSolid />,
              href: "/sale/issue-item",
              permission: PERMISSIONS.ISSUE_ITEM,
            },
            {
              name: "Received Item",
              icon: <LiaClipboardListSolid />,
              href: "/sale/received-item",
              permission: PERMISSIONS.RECEIVED_ITEM,
            },
            {
              name: "Damage Item",
              icon: <GiBrokenBone />,
              href: "/sale/damage-item",
              permission: PERMISSIONS.DAMAGE_ITEM,
            },
            {
              name: "Stock Report",
              icon: <LiaClipboardListSolid />,
              href: "/sale/stock-report",
              permission: PERMISSIONS.STOCK_REPORT,
            },
            {
              name: "Seller List",
              icon: <LiaClipboardListSolid />,
              href: "/sale/seller",
              permission: PERMISSIONS.SELLER_LIST,
            },
            {
              name: "Seller Stock",
              icon: <LiaClipboardListSolid />,
              href: "/sale/seller-stock",
              permission: PERMISSIONS.SELLER_STOCK,
            },
            {
              name: "Purchase Order",
              icon: <LiaClipboardListSolid />,
              href: "/sale/purchase-order",
              permission: PERMISSIONS.PURCHASE_ORDER,
            },
          ],
        },
        {
          name: "Time Table",
          icon: <MdAccountBalance />,
          permission: PERMISSIONS.TIME_TABLE,
          key: "time_table",
          href: "/time-table",
          children: [
            {
              name: "Preiod Master",
              icon: <GiExpense />,
              href: "/time-table/create-period",
              permission: PERMISSIONS.PERIOD_MASTER,
            },
            {
              name: "Teacher Registration",
              icon: <GiExpense />,
              href: "/time-table/teacher-registration",
              permission: PERMISSIONS.TEACHER_REGISTRATION,
            },
            {
              name: "Assign Period",
              icon: <GiExpense />,
              href: "/time-table/assignperiod",
              permission: PERMISSIONS.ASSIGN_PERIOD,
            },
            {
              name: "Teacher Timetable",
              icon: <GiExpense />,
              href: "/time-table/teacher-time-table",
              permission: PERMISSIONS.TEACHER_TIME_TABLE,
            },
            {
              name: "Class Timetable",
              icon: <GiExpense />,
              href: "/time-table/student-time-table",
              permission: PERMISSIONS.CLASS_TIME_TABLE,
            },
            {
              name: "Temporary Time Table",
              icon: <GiExpense />,
              href: "/time-table/time-table-adjust",
              permission: PERMISSIONS.TIME_TABLE_ADJUST,
            },
          ],
        },
        {
          name: "Mobile App",
          icon: <HiDevicePhoneMobile />,
          permission: PERMISSIONS.MOBILE_APP,
          key: "app",
          children: [
            {
              name: "Syllabus",
              icon: <BiPhotoAlbum />,
              href: "/syllabus/CreateSyllabus",
              permission: PERMISSIONS.SYLLABUS,
            },
            {
              name: "School Events",
              icon: <BiPhotoAlbum />,
              href: "/app/school-album",
              permission: PERMISSIONS.SCHOOL_ALBUM,
            },
            {
              name: "Staff (App User)",
              icon: <LuUsers />,
              href: "/app/staff",
              permission: PERMISSIONS.STAFF,
            },
            {
              name: "Staff Prmotion",
              icon: <LuUsers />,
              href: "/app/staff-promote",
              permission: PERMISSIONS.STAFF,
            },
            {
              name: "Class Teacher",
              icon: <GiTeacher />,
              href: "/app/class-teacher",
              permission: PERMISSIONS.CLASS_TEACHER,
            },
            {
              name: "Subject Teacher",
              icon: <LuUsers />,
              href: "/app/subject-teacher",
              permission: PERMISSIONS.SUBJECT_TEACHER,
            },
            {
              name: "Teacher Leave Request",
              icon: <LuUsers />,
              href: "/admin/teacher-leave-request",
              permission: PERMISSIONS.TEACHER_LEAVE_REQUEST,
            },
            {
              name: "App Activation",
              icon: <MdOutlineMobileFriendly />,
              href: "/app/app-activation",
              permission: PERMISSIONS.APP_ACTIVATION,
            },
            {
              name: "Student (App User)",
              icon: <MdOutlineVerifiedUser />,
              href: "/app/activated-student",
              permission: PERMISSIONS.ACTIVATED_STUDENT,
            },

            {
              name: "Chapter",
              icon: <LuUsers />,
              href: "/app/chapter",
              permission: PERMISSIONS.CHAPTER,
            },
            {
              name: "Homework",
              icon: <MdOutlineHomeWork />,
              href: "/app/homework",
              permission: PERMISSIONS.HOMEWORK,
            },
            {
              name: "Calender",
              icon: <IoCalendarOutline />,
              href: "/app/calender",
              permission: PERMISSIONS.CALENDER,
            },
            {
              name: "Notice Board",
              icon: <HiOutlineClipboardDocumentList />,
              href: "/app/notice-board",
              permission: PERMISSIONS.NOTICE_BOARD,
            },
            {
              name: "News Highlight",
              icon: <HiOutlineClipboardDocumentList />,
              href: "/app/news-highlight",
              permission: PERMISSIONS.NEWS_HIGHLIGHT,
            },
            {
              name: "News POPUP",
              icon: <HiOutlineClipboardDocumentList />,
              href: "/app/news-highlight/image",
              permission: PERMISSIONS.NEWS_POPUP,
            },
            {
              name: "App Message",
              icon: <TbDeviceMobileMessage />,
              href: "/app/app-messages",
              permission: PERMISSIONS.APP_MESSAGE,
            },
            {
              name: "Time Table",
              icon: <TbAlertSquare />,
              href: "/app/time-table",
              permission: PERMISSIONS.TIME_TABLE_MOBILE_APP,
            },
            {
              name: "Grevience List",
              icon: <TbAlertSquare />,
              href: "/app/grevience",
              permission: PERMISSIONS.GREVINCE_LIST,
            },
          ],
        },
      ];
