export const STDFIELDS = [
  { id: "srNo", name: "SR No" },
  { id: "admissionNo", name: "Admission No." },
  { id: "admissionDate", name: "Admission Date" },
  { id: "formNo", name: "Form No." },
  { id: "studentName", name: "Student Name" },
  { id: "studentContact", name: "Student Contact" },
  { id: "studentEmail", name: "Student Email" },
  { id: "dob", name: "DOB" },
  { id: "aadharNo", name: "Aadhar No" },
  { id: "gender", name: "Gender" },
  { id: "classMasterId", name: "Class" },
  { id: "streamMasterId", name: "Stream" },
  { id: "sectionMasterId", name: "Section" },
  { id: "selectedSubjects", name: "Subjects" },
  { id: "admissionSource", name: "Admission Source" },
  { id: "applicationType", name: "Application Type" },
  { id: "isRTE", name: "Is RTE" },
  { id: "houseMasterId", name: "House" },
  { id: "religion", name: "Religion" },
  { id: "category", name: "Category" },
  { id: "handicap", name: "Handicap" },
  { id: "bloodGroup", name: "Blood Group" },
  { id: "fatherName", name: "Father Name" },
  { id: "fatherContact", name: "Father Contact" },
  { id: "occupation", name: "Occupation" },
  { id: "income", name: "Income" },
  { id: "motherName", name: "Mother Name" },
  { id: "motherContact", name: "Mother Contact" },
  { id: "address", name: "Address" },
  { id: "guardianName", name: "Guardian Name" },
  { id: "guardianContact", name: "Guardian Contact" },
  { id: "guardianEmail", name: "Guardian Email" },
  { id: "correspondingAddress", name: "Corresponding Address" },
  { id: "prevSrNo", name: "Prev SrNo" },
  { id: "prevClass", name: "Prev Class" },
  { id: "prevStream", name: "Prev Stream" },
  { id: "prevSchool", name: "Prev School" },
  { id: "prevMaxmarks", name: "Prev Max Marks" },
  { id: "prevObtainmarks", name: "Prev ObtainMarks" },
  { id: "prevPercentmarks", name: "Prev Percent Marks" },
  { id: "prevAddress", name: "Prev School Address" },
  { id: "openingAmount", name: "Opening Amount" },
  { id: "fees", name: "Fees" },
  { id: "apparId", name: "Appar Id" },
];
