export const STOCKFIELDS = [
    { id: "name", name: "Book Name" },
    { id: "author", name: "Author" },
    { id: "isbn", name: "ISBN" },
    { id: "bookType", name: "Book Type" },
    { id: "genre", name: "Genre" },
    { id: "publisher", name: "Publisher" },
    { id: "yearOfPublication", name: "Year Of Publication" },
    { id: "edition", name: "Edition" },
    { id: "language", name: "Language" },
    { id: "damageAmount", name: "Damage Amount" },
    { id: "lostAmount", name: "Lost Amount" },
    { id: "description", name: "Description" },
    { id: "shelf", name: "Shelf Location" },
    { id: "quantity", name: "Quantity" },
    { id: "price", name: "Price" },
    { id: "stockDate", name: "Stock Date" },
    { id: "billDate", name: "Bill Date" },
    { id: "billNo", name: "Bill No" },
    { id: "total", name: "Total" },
    { id: "discount", name: "Discount" },
]